### ISSUE TITLE
Something went wrong: models were not installed.

### ISSUE THREAD

**Issue by RickVM** [opensource-spraakherkenning-nl/Kaldi_NL#10]
After installing Kaldi and all the prerequisites I ran /configure.sh.
After entering my kaldi root and src in the script I tell it to store the models at
/home/rick/Documents/Kaldi_NL/models/   
(no ~)

Script then starts downloading and doing a bunch of stuff, after a while I get the message: " Something went wrong: models were not installed"

Last few lines were:
```Models/NL/UTwente/HMI/AM/CGN_large/nnet2_online/nnet_ms_a_tri4_ami_online/v1.0/tree
Models/NL/UTwente/HMI/AM/CGN_large/nnet3_online/tdnn_cleaned/v1.0/frame_subsampling_factor
Models/NL/UTwente/HMI/AM/CGN_nomis/nnet_bn/dnn8f_pretrain_dbn_dnn_smbr/v1.0/final.feature_transform
Models/NL/UTwente/HMI/AM/CGN_large/nnet2_online/nnet_ms_a_tri4_ami_smbr_online/v1.0/conf/.fixed
Models/NL/UTwente/HMI/AM/CGN_nomis/fmllr_bn/dnn8a_bn-feat/v1.0/nnet/nnet_iter13_learnrate1.5625e-05_tr2.0319_cv2.1793_final_
Models/NL/UTwente/HMI/AM/CGN_large/nnet3_online/tdnn_cleaned/v1.0/ivector_extractor/online_cmvn.conf
Something went wrong: models were not installed.
```

If i open the folder it is empty.
No messages showing anything going wrong prior to the above. 
The tar file seems to have been successfully downloaded according to my shell.
What went wrong and how can I Fix this?
I'd like to try out the model with a small benchmark to assess usabilty for a project.

**Comment by insad** [comment]
1. did you modify KALDI_ROOT in path.sh ?
2. does your script have enough rights to create folders / elements ?

**Comment by proycon** [comment]
(closing this due to being an old issue without further response)
