### ISSUE TITLE
No speech found, exiting.

### ISSUE THREAD

**Issue by JeromeNi** [opensource-spraakherkenning-nl/Kaldi_NL#11]
Hi,

I've successfully(I think) built the model and generated decode.sh using configure.sh. However, upon running decode.sh with a speech folder in CGN, I got an error like this:
`
 ./decode.sh /home/jerome/Documents/20151207_CGN_2_0_3/CGN_2.0.3/data/audio/wav/comp-o/nl output
Argument /home/jerome/Documents/20151207_CGN_2_0_3/CGN_2.0.3/data/audio/wav/comp-o/nl is a directory, copying contents..  done
Diarization completed in 0:00:11 (CPU: 0:00:09), Memory used: 6 MB                
Split 561 source files into 0 segment                              
cat: output/intermediate/data/ALL/spk2utt: No such file or directory
No speech found, exiting.
`
Any idea what went wrong?

Also, if I want to see the WER of the decoding, how can I pass in the ground truth speech transcription, and in what format?

Thanks!

**Comment by joukestaring** [comment]
Did you find the solution for the "no speech found, exiting." issue? I am dealing with the same problem right now

**Comment by JepettoA** [comment]
I have the same issue.

**Comment by ExploHash** [comment]
Same issue here, can one of the maintainers help maybe?

**Comment by proycon** [comment]
@JBeaart: Did you mention that you found a solution to this issue?

I wonder if it still occurs with the latest version, there have been some improvements, error catching and feedback was very suboptimal and has been improved a bit now.

**Comment by ExploHash** [comment]
@proycon I figured I was commenting too quickly so that's why I removed my comment. But in my case it was because I didn't have the right .wav settings. Mono 16 bit signed little endian 8000 bitrate is working now :). Example: `arecord -f S16_LE -r 8000 test.wav`

**Comment by proycon** [comment]
Good to know! That may help others who had this issue too :) 

(please reopen if the issue persists for others)
