### ISSUE TITLE
Re-containerize Kaldi_NL without LaMachine

### ISSUE THREAD

**Issue by proycon** [opensource-spraakherkenning-nl/Kaldi_NL#22]
In light of proycon/LaMachine#214 a new container build that is standalone (no longer using LaMachine) needs to be implemented.

Kaldi poses two extra challenges:

* The image is huge (30GB) due to all the models (and a fair amount of cruft)
* I'd like to use Alpine as a basis though it's still a bit unsure whether all kaldi components compile nicely against musl. Moreover, this is only for production scenarios that do not require a GPU (e.g. no training).

**Comment by proycon** [comment]
We'll see if we can increase the granularity of the models so that only the models that are needed can be selected, and we'll move those into separate container mounts that can be orchestrated together. This should make things more scalable and less bulky.

(discussed with @roelandordelman and @jblom)

**Comment by proycon** [comment]
Change of plan: I'm not going to use Alpine Linux as I expect too many issues with non-GNU versions of tools. I'll just build on the image kaldi itself provides (debian).

**Comment by sirifarif** [comment]
@proycon Do you have a chance to look at [this](https://github.com/laurensw75/docker-Kaldi-NL/blob/master/Dockerfile) Docker file?
It might help.

**Comment by proycon** [comment]
Thanks Arif! I've seen that one indeed, it provides a good reference (though it adds more than I want, like all the gstreamer stuff)

**Comment by jblom** [comment]
Ah yes the gstreamer stuff I also wanted to get rid of in my old attempt to get a leaner kaldi_NL image. I found this image I made back then (Note: 2 colleagues Willem/Jan-Willem also used a kaldi_NL image in their workflows): 

<img width="998" alt="Schermafbeelding 2022-02-18 om 08 52 48" src="https://user-images.githubusercontent.com/917310/154641073-d566c877-36cc-4f29-8f07-e054d76aa5d7.png">

**Comment by proycon** [comment]
I've completed the re-containerization now, hopefully addressing all concerns we had and resulting in leaner images. Please see the release notes for all details: https://github.com/opensource-spraakherkenning-nl/Kaldi_NL/releases/tag/v0.4.0

Experiments using the new containers would be much appreciated so we can fix any issues that may arise! The idea is that any further containers, e.g. with gstreamer, DANE, the asr_nl webservice or whatever else, can easily base off the ones we provided now.

PS: @jblom nice schema, perhaps we might want to make one for the new situation?

**Comment by jblom** [comment]
@proycon good to hear! Hope to test the new lean image this week. About the graphic: yes it might be nice to provide such an image (internal image structure + part with known `FROM` users of the image) at some point in the Kaldi_NL repo,  but first I'd say a nice README with examples on how to use the image would be more useful (I can e.g. provide examples for k8s and refer to a fully fledged DANE ASR setup, e.g. helm chart).

But first let's test it out well.
