### ISSUE TITLE
Hoe kan ik getallen in cijfers laten herkennen ipv als woorden?

### ISSUE THREAD

**Issue by kkoenen** [opensource-spraakherkenning-nl/Kaldi_NL#7]
KaldiNL werkt prima op mijn CentOS systeem. Ik wil echter getallen (bijv 152.200) laten opschrijven in de transcriptie als getal (dus in cijfers), in plaats van honderdtweeenvijftigduizend...

Hoe kan ik dat het best doen? Zijn er aanvullingen op het LM beschikbaar of verwacht, die dit mogelijk maken?

Dank!

**Comment by proycon** [comment]
Sorry you didn't get a reply from the previous maintainers, I assume this question is outdated by now so am closing it. Please re-open if still relevant (I don't have the answer myself though but others may).
